apt:
  preserve_sources_list: false
  primary:
    - arches:
        - default
      uri: '${nexus_proxy_url}/repository/ubuntu/'

  security:
    - arches:
        - default
      uri: '${nexus_proxy_url}/repository/ubuntu-security/'
  sources_list: |
      deb [trusted=yes] $PRIMARY $RELEASE main restricted universe multiverse
      deb [trusted=yes] $PRIMARY $RELEASE-updates main restricted universe multiverse
      deb [trusted=yes] $SECURITY $RELEASE main restricted universe multiverse
      deb [trusted=yes] ${nexus_proxy_url}/repository/apt-pypi/ $RELEASE main restricted universe multiverse
bootcmd:
  - sudo tee /etc/pip.conf > dev/null <<'EOF'
    [global]
    index = ${nexus_proxy_url}/repository/pypi/pypi
    index-url = ${nexus_proxy_url}/repository/pypi/simple
    trusted-host = ${nexus_proxy_url}
    EOF
