apt:
  preserve_sources_list: false
  primary:
    - arches:
        - default
      uri: '${nexus_proxy_url}/ubuntu-proxy-repo/'

  security:
    - arches:
        - default
      uri: '${nexus_proxy_url}/ubuntu-security-proxy-repo/'
  sources_list: |
      deb [trusted=yes] $PRIMARY $RELEASE main restricted universe multiverse
      deb [trusted=yes] $PRIMARY $RELEASE-updates main restricted universe multiverse
      deb [trusted=yes] $SECURITY $RELEASE main restricted universe multiverse
      deb [trusted=yes] ${nexus_proxy_url}/pypi-proxy-repo/ $RELEASE main restricted universe multiverse
