apt:
  preserve_sources_list: false
  primary:
    - arches:
        - default
      uri: '${nexus_proxy_url}/ubuntu/'

  security:
    - arches:
        - default
      uri: '${nexus_proxy_url}/ubuntu-security/'
  sources_list: |
      deb [trusted=yes] $PRIMARY $RELEASE main restricted universe multiverse
      deb [trusted=yes] $PRIMARY $RELEASE-updates main restricted universe multiverse
      deb [trusted=yes] $SECURITY $RELEASE main restricted universe multiverse
      deb [trusted=yes] ${nexus_proxy_url}/apt-pypi/ $RELEASE main restricted universe multiverse
