version: "3"

services:
  server:
    image: gitea/gitea:1.14.2
    container_name: gitea
    environment:
        - USER_UID=1000
        - USER_GID=1000
        - GITEA__server__APP_DATA_PATH=/data
        # - GITEA__database__DB_TYPE=mysql
        # - GITEA__database__HOST=db:3306
        # - GITEA__database__NAME=gitea
        # - GITEA__database__USER=gitea
        # - GITEA__database__PASSWD=gitea
    restart: always
    volumes:
        - ${WEBAPP_STORAGE_HOME}/data:/data
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
    ports:
        - "3000:3000"
        - "222:22"
   