---
#cloud-config
package_upgrade: true
apt:
  sources:
    docker.list:
      source: deb [arch=amd64]
        https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      keyserver: hkp://keyserver.ubuntu.com:80

packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose
  - gnupg2
  - pass

write_files:
  # a weekly cron job to have docker free disk space
  - path: /etc/cron.weekly/docker-prune
    content: |
      #!/bin/bash
      set -o errexit
      docker system prune -f
    permissions: '0755'
  # ensure Nexus doesn't create default repositories
  - path: /etc/nexus-data/nexus.properties
    content: |
      nexus.skipDefaultRepositories=true
    permissions: '0755'

runcmd:
  - export DEBIAN_FRONTEND=noninteractive
  # Run the nexus container (exposing port 8081 and mapping volume for nexus config)
  - docker run -d
    -p 8081:8081
    -v /etc/nexus-data:/nexus-data
    --restart always
    --name nexus
    --log-driver local
    sonatype/nexus3
