---
name: "run_command"
description: "Run a command in a devcontainer"
inputs:
    USE_ENV_VARS_NOT_FILES:
      description: "Use ENV variables rather than a file."
      required: false
      default: "true"
    DOCKER_BUILDKIT:
      description: "Use Moby Buildkit."
      required: false
      default: "1"
    TF_INPUT:
      description: "Make Terraform fail if missing variables."
      required: false
      default: "0"
    TF_IN_AUTOMATION:
      description: "Terraform should not provide hints in the console."
      required: false
      default: "1"
    COMMAND:
      description: "The command you want to run in the Devcontainer."
      required: true
    DISPLAY_NAME:
      description: "The friendly name of the command."
      required: true
    ACTIONS_ACR_NAME:
      description: "The Azure Container registry name that the devcontainer is stored in."
      required: true
    ACTIONS_ACR_PASSWORD:
      description: "The Azure Container registry password for the devcontainer."
      required: true
    ARM_TENANT_ID:
      description: "Azure Tenant Id."
      required: true
    ARM_CLIENT_ID:
      description: "Azure user Id. This user needs User Access Administrator permission as minimum."
      required: true
    ARM_CLIENT_SECRET:
      description: "Azure user password."
      required: true
    ARM_SUBSCRIPTION_ID:
      description: "Azure Subscription Id."
      required: true
    RESOURCE_LOCATION:
      description: "The friendly name of the command."
      required: true
    RESOURCE:
      description: "The friendly name of the command."
      required: true
    AUTH_TENANT_ID:
      description: "The friendly name of the command."
      required: true
    TEST_APP_ID:
      description: "The friendly name of the command."
      required: true
    TEST_USER_NAME:
      description: "The friendly name of the command."
      required: true
    TEST_USER_PASSWORD:
      description: "The friendly name of the command."
      required: true
    TEST_WORKSPACE_APP_ID:
      description: "The friendly name of the command."
      required: true
    TRE_ID:
      description: "The friendly name of the command."
      required: true
    TF_VAR_location:
      description: "The friendly name of the command."
      required: true
    TF_VAR_tre_id:
      description: "The friendly name of the command."
      required: true
    TF_VAR_terraform_state_container_name:
      description: "The friendly name of the command."
      required: true
    TF_VAR_mgmt_resource_group_name:
      description: "The friendly name of the command."
      required: true
    TF_VAR_mgmt_storage_account_name:
      description: "The friendly name of the command."
      required: true
    TF_VAR_core_address_space:
      description: "The friendly name of the command."
      required: true
    TF_VAR_tre_address_space:
      description: "The friendly name of the command."
      required: true
    TF_VAR_swagger_ui_client_id:
      description: "The friendly name of the command."
      required: true
    TF_VAR_aad_tenant_id:
      description: "The friendly name of the command."
      required: true
    TF_VAR_api_client_id:
      description: "The friendly name of the command."
      required: true
    TF_VAR_api_client_secret:
      description: "The friendly name of the command."
      required: true
    TF_VAR_api_app_service_plan_sku_tier:
      description: "The friendly name of the command."
      required: false
      default: "PremiumV3"
    TF_VAR_api_app_service_plan_sku_size:
      description: "The friendly name of the command."
      required: false
      default: "P1v3"
    TF_VAR_acr_name:
      description: "The friendly name of the command."
      required: true
    LOCATION:
      description: "The friendly name of the command."
      required: true
    TRE_URL:
      description: "The friendly name of the command."
      required: false
    BUNDLE_TYPE:
      description: "The friendly name of the command."
      required: false
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker BuildKit
      uses: docker/setup-buildx-action@v1

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.ACTIONS_ACR_NAME }}.azurecr.io
        username: ${{ inputs.ACTIONS_ACR_NAME }}
        password: ${{ inputs.ACTIONS_ACR_PASSWORD }}

    - name: Run command in DevContainer
      shell: bash
      env:
        ACTIONS_ACR_NAME: ${{ inputs.ACTIONS_ACR_NAME }}
        ACTIONS_ACR_PASSWORD: ${{ inputs.ACTIONS_ACR_PASSWORD }}
        ARM_TENANT_ID: "${{ inputs.ARM_TENANT_ID }}"
        ARM_CLIENT_ID: "${{ inputs.ARM_CLIENT_ID }}"
        ARM_CLIENT_SECRET: "${{ inputs.ARM_CLIENT_SECRET }}"
        ARM_SUBSCRIPTION_ID: "${{ inputs.ARM_SUBSCRIPTION_ID }}"
        RESOURCE_LOCATION: "${{ inputs.RESOURCE_LOCATION }}"
        RESOURCE: "${{ inputs.RESOURCE }}"
        AUTH_TENANT_ID: "${{ inputs.AUTH_TENANT_ID }}"
        CLIENT_ID: "${{ inputs.TEST_APP_ID }}"
        USERNAME: "${{ inputs.TEST_USER_NAME }}"
        PASSWORD: "${{ inputs.TEST_USER_PASSWORD }}"
        ACR_NAME: ${{ inputs.TF_VAR_acr_name }}
        TRE_URL:
          "https://${{inputs.TRE_ID}}.${{inputs.LOCATION}}.cloudapp.azure.com"
        TEST_WORKSPACE_APP_ID: "${{ inputs.TEST_WORKSPACE_APP_ID }}"
        TRE_ID: "${{ inputs.TF_VAR_tre_id }}"
        TF_VAR_tre_id: "${{ inputs.TF_VAR_tre_id }}"
        TF_VAR_location: ${{ inputs.TF_VAR_location }}
        TF_VAR_terraform_state_container_name:
          ${{ inputs.TF_VAR_terraform_state_container_name }}
        TF_VAR_mgmt_resource_group_name: ${{ inputs.TF_VAR_mgmt_resource_group_name }}
        TF_VAR_mgmt_storage_account_name:
          ${{ inputs.TF_VAR_mgmt_storage_account_name }}
        TF_VAR_core_address_space: ${{ inputs.TF_VAR_core_address_space }}
        TF_VAR_tre_address_space: ${{ inputs.TF_VAR_tre_address_space }}
        TF_VAR_swagger_ui_client_id: "${{ inputs.TF_VAR_swagger_ui_client_id }}"
        TF_VAR_aad_tenant_id: "${{ inputs.TF_VAR_aad_tenant_id }}"
        TF_VAR_api_client_id: "${{ inputs.TF_VAR_api_client_id }}"
        TF_VAR_api_client_secret: "${{ inputs.TF_VAR_api_client_secret }}"
        TF_VAR_api_app_service_plan_sku_tier: "${{ inputs.TF_VAR_api_app_service_plan_sku_tier }}"
        TF_VAR_api_app_service_plan_sku_size: "${{ inputs.TF_VAR_api_app_service_plan_sku_size }}"
        TF_VAR_acr_name: ${{ inputs.TF_VAR_acr_name }}
        LOCATION: ${{ inputs.TF_VAR_location }} # scripts are using this too
      run: |
        docker run --rm --mount \
          "type=bind,src=${{ github.workspace }},dst=/workspaces/tre" \
          -v /var/run/docker.sock:/var/run/docker.sock \
          --workdir /workspaces/tre \
          --user vscode \
          -e TF_INPUT \
          -e TF_IN_AUTOMATION \
          -e USE_ENV_VARS_NOT_FILES \
          -e ARM_CLIENT_ID \
          -e ARM_CLIENT_SECRET \
          -e ARM_TENANT_ID \
          -e ARM_SUBSCRIPTION_ID \
          -e TF_VAR_location \
          -e TF_VAR_terraform_state_container_name \
          -e TF_VAR_mgmt_storage_account_name \
          -e TF_VAR_mgmt_resource_group_name \
          -e TF_VAR_tre_id \
          -e ACR_NAME \
          -e TF_VAR_acr_name \
          -e TF_VAR_aad_tenant_id \
          -e TF_VAR_api_client_id \
          -e TF_VAR_api_client_secret \
          -e TF_VAR_api_app_service_plan_sku_tier \
          -e TF_VAR_api_app_service_plan_sku_size \
          -e TF_VAR_swagger_ui_client_id \
          -e TF_VAR_core_address_space \
          -e TF_VAR_tre_address_space \
          -e BUNDLE_TYPE \
          -e RESOURCE_LOCATION \
          -e RESOURCE \
          -e AUTH_TENANT_ID \
          -e CLIENT_ID \
          -e USERNAME \
          -e PASSWORD \
          -e TRE_ID \
          -e TEST_WORKSPACE_APP_ID \
          '${{ inputs.ACTIONS_ACR_NAME }}.azurecr.io/tredev:latest' \
        bash -c "${{ inputs.COMMAND }}"
