name: Docker build and push

on:
  pull_request:
    paths:
      - core/**
  push:
    branches: [ develop, main ]
    paths:
      - core/**
  workflow_dispatch:

jobs:
  docker_build:
    name: Build management-api
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Packages Container registry
        uses: docker/login-action@v1 
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & publish image
        env:
          DOCKER_BUILDKIT: 1
          REPOSITORY_NAME: docker.pkg.github.com/microsoft/azuretre/management-api
        run: |
          echo $GITHUB_REF
          if [ $GITHUB_EVENT_NAME == 'push' ] && [ $GITHUB_REF == 'refs/heads/develop' ]; then
            TAG='develop-latest'
          elif [ $GITHUB_EVENT_NAME == 'push' ] && [ $GITHUB_REF == 'refs/heads/main' ]; then
            TAG='main-latest'
          else
            TAG=$GITHUB_SHA
          fi

          docker build -t ${{ env.REPOSITORY_NAME}}:$TAG core/api/  
          docker push ${{ env.REPOSITORY_NAME}}:$TAG