---
name: Run a command in a devcontainer
on:
  workflow_call:
    inputs:
      USE_ENV_VARS_NOT_FILES:
        required: true
        type: boolean
      DOCKER_BUILDKIT:
        required: true
        type: number
      TF_INPUT:
        required: true
        type: number
      TF_IN_AUTOMATION:
        required: true
        type: number
      COMMAND:
        required: true
        type: string
      DISPLAY_NAME:
        required: true
        type: string
    secrets:
      ACTIONS_ACR_NAME:
        required: true
      ACTIONS_ACR_PASSWORD:
        required: true
      ARM_TENANT_ID:
        required: true
      ARM_CLIENT_ID:
        required: true
      ARM_CLIENT_SECRET:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true
      RESOURCE_LOCATION:
        required: true
      RESOURCE:
        required: true
      AUTH_TENANT_ID:
        required: true
      CLIENT_ID:
        required: true
      USERNAME:
        required: true
      PASSWORD:
        required: true
      TEST_WORKSPACE_APP_ID:
        required: true
      TRE_ID:
        required: true
      TF_VAR_location:
        required: true
      TF_VAR_tre_id:
        required: true
      TF_VAR_terraform_state_container_name:
        required: true
      TF_VAR_mgmt_resource_group_name:
        required: true
      TF_VAR_mgmt_storage_account_name:
        required: true
      TF_VAR_core_address_space:
        required: true
      TF_VAR_tre_address_space:
        required: true
      TF_VAR_swagger_ui_client_id:
        required: true
      TF_VAR_aad_tenant_id:
        required: true
      TF_VAR_api_client_id:
        required: true
      TF_VAR_api_client_secret:
        required: true
      TF_VAR_api_app_service_plan_sku_tier:
        required: true
      TF_VAR_api_app_service_plan_sku_size:
        required: true
      TF_VAR_acr_name:
        required: true
      ACR_NAME:
        required: true
      LOCATION:
        required: true
      TRE_URL:
        required: true
      BUNDLE_TYPE:
        required: false

jobs:
  run_command_in_dev_container:
    name: ${{ inputs.DISPLAY_NAME }}
    runs-on: ubuntu-latest
    environment: Dev
    if: |
      github.event.name == 'schedule'
      || github.event_name == 'push'
      || github.event_name == 'workflow_dispatch'
      || contains(github.event.pull_request.labels.*.name, 'safe to test')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker BuildKit
        uses: docker/setup-buildx-action@v1

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACTIONS_ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACTIONS_ACR_NAME }}
          password: ${{ secrets.ACTIONS_ACR_PASSWORD }}

      - name: Run command in DevContainer
        shell: bash
        run: |
          docker run --rm --mount \
            "type=bind,src=${{ github.workspace }},dst=/workspaces/tre" \
            -v /var/run/docker.sock:/var/run/docker.sock \
            --workdir /workspaces/tre \
            --user vscode \
            -e TF_INPUT \
            -e TF_IN_AUTOMATION \
            -e USE_ENV_VARS_NOT_FILES \
            -e ARM_CLIENT_ID \
            -e ARM_CLIENT_SECRET \
            -e ARM_TENANT_ID \
            -e ARM_SUBSCRIPTION_ID \
            -e TF_VAR_location \
            -e TF_VAR_terraform_state_container_name \
            -e TF_VAR_mgmt_storage_account_name \
            -e TF_VAR_mgmt_resource_group_name \
            -e TF_VAR_tre_id \
            -e ACR_NAME \
            -e TF_VAR_acr_name \
            -e TF_VAR_aad_tenant_id \
            -e TF_VAR_api_client_id \
            -e TF_VAR_api_client_secret \
            -e TF_VAR_api_app_service_plan_sku_tier \
            -e TF_VAR_api_app_service_plan_sku_size \
            -e TF_VAR_swagger_ui_client_id \
            -e TF_VAR_core_address_space \
            -e TF_VAR_tre_address_space \
            -e BUNDLE_TYPE \
            -e RESOURCE_LOCATION \
            -e RESOURCE \
            -e AUTH_TENANT_ID \
            -e CLIENT_ID \
            -e USERNAME \
            -e PASSWORD \
            -e TRE_ID \
            -e TEST_WORKSPACE_APP_ID \
            '${{ secrets.ACTIONS_ACR_NAME }}.azurecr.io/tredev:latest' \
          bash -c "${{ inputs.COMMAND }}"
