---
name: End to End Tests

on:
  push:
    branches: [ross/ActionsInDevContainer]
  workflow_dispatch:

env:
  USE_ENV_VARS_NOT_FILES: true
  DOCKER_BUILDKIT: 1
  TF_INPUT: 0 # No input supplied to Terraform
  TF_IN_AUTOMATION: 1 # No prompts

jobs:
  e2e_tests:
    uses: ./.github/workflows/devcontainer_run_command.yml
    with:
      USE_ENV_VARS_NOT_FILES: true
      DOCKER_BUILDKIT: 1
      TF_INPUT: 0 # No input supplied to Terraform
      TF_IN_AUTOMATION: 1 # No prompts
      DISPLAY_NAME: "Run e2e Tests"
      COMMAND: "make test-e2e"
    secrets:
      ACTIONS_ACR_NAME: ${{ secrets.ACTIONS_ACR_NAME }}
      ACTIONS_ACR_PASSWORD: ${{ secrets.ACTIONS_ACR_PASSWORD }}
      ARM_TENANT_ID: "${{ secrets.ARM_TENANT_ID }}"
      ARM_CLIENT_ID: "${{ secrets.ARM_CLIENT_ID }}"
      ARM_CLIENT_SECRET: "${{ secrets.ARM_CLIENT_SECRET }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.ARM_SUBSCRIPTION_ID }}"
      RESOURCE_LOCATION: "${{ secrets.LOCATION }}"
      RESOURCE: "${{ secrets.API_CLIENT_ID }}"
      AUTH_TENANT_ID: "${{ secrets.AAD_TENANT_ID }}"
      CLIENT_ID: "${{ secrets.TEST_APP_ID }}"
      USERNAME: "${{ secrets.TEST_USER_NAME }}"
      PASSWORD: "${{ secrets.TEST_USER_PASSWORD }}"
      ACR_NAME: ${{ secrets.ACR_NAME }}
      TRE_URL:
        "https://${{secrets.TRE_ID}}.${{secrets.LOCATION}}.cloudapp.azure.com"
      TRE_ID: "${{ secrets.TRE_ID }}"
      TEST_WORKSPACE_APP_ID: "${{ secrets.TEST_WORKSPACE_APP_ID }}"
      TF_VAR_location: ${{ secrets.LOCATION }}
      TF_VAR_tre_id: ${{ secrets.TRE_ID }}
      TF_VAR_terraform_state_container_name:
        ${{ secrets.TF_STATE_CONTAINER }}
      TF_VAR_mgmt_resource_group_name: ${{ secrets.MGMT_RESOURCE_GROUP }}
      TF_VAR_mgmt_storage_account_name:
        ${{ secrets.STATE_STORAGE_ACCOUNT_NAME }}
      TF_VAR_core_address_space: ${{ secrets.CORE_ADDRESS_SPACE }}
      TF_VAR_tre_address_space: ${{ secrets.TRE_ADDRESS_SPACE }}
      TF_VAR_swagger_ui_client_id: "${{ secrets.SWAGGER_UI_CLIENT_ID }}"
      TF_VAR_aad_tenant_id: "${{ secrets.AAD_TENANT_ID }}"
      TF_VAR_api_client_id: "${{ secrets.API_CLIENT_ID }}"
      TF_VAR_api_client_secret: "${{ secrets.API_CLIENT_SECRET }}"
      TF_VAR_api_app_service_plan_sku_tier: "PremiumV3"
      TF_VAR_api_app_service_plan_sku_size: "P1v3"
      TF_VAR_acr_name: ${{ secrets.ACR_NAME }}
      LOCATION: ${{ secrets.LOCATION }} # scripts are using this too
