name: flag_external_pr

on:
  pull_request_target:
    types: [opened] # only run on new PRs
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment
    # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#issue_comment

jobs:
  check_author:
    name: Check PR author
    runs-on: ubuntu-latest
    steps:
      - id: check_command
        name: Check for a command using GitHub script
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const script = require('./.github/workflows/script.js')
            script.labelAsExternalIfAuthorDoesNotHaveWriteAccess({core, context, github});
