name: Nightly Cleanup

on:
  schedule:
    # 1am https://crontab.guru/#0_1_*_*_*
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  nightly_cleanup:
    runs-on: ubuntu-latest
    environment: Dev

    steps:
    - name: Clean management-api
      uses: smartsquaregmbh/delete-old-packages@v0.3.1
      with:
        # Regex to delete all images created as a result of PRs, i.e. tagged with git commit SHA, 
        # e.g. ed6da1da779694ad13aae193dcc94ec7fa59786c to keep the package registry clean. 
        version-pattern: "\\b[0-9a-f]{5,40}\\b" # The regex needs to be escaped!
        names: |
          management-api
        keep: 0