name: AzureTRE Continuous Delivery

on:
  push:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Dev
    env:
      TF_VAR_environment: "dev"
      TF_VAR_address_space: "10.0.0.0/16"
      TF_VAR_state_storage: "stgmsfttretfstate"
      TF_VAR_mgmt_res_group: "rg-msft-tre-tfstate"
      TF_VAR_state_container: "tfstate"
      TF_VAR_resource_name_prefix: "msfttre"
      TF_VAR_location: "westeurope"
      TF_VAR_image_tag: "v1"

    steps:
    - uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Make .env files
      uses: azure/CLI@v1
      with:
        azcliversion: 2.20.0
        inlineScript: |
          env_file="devops/terraform/.env"
          cat <<EOF > $env_file
          TF_VAR_state_storage=${{ env.TF_VAR_state_storage }}
          TF_VAR_mgmt_res_group=${{ env.TF_VAR_mgmt_res_group }}
          TF_VAR_state_container=${{ env.TF_VAR_state_container }}
          TF_VAR_location=${{ env.TF_VAR_resource_name_prefix }}
          TF_VAR_resource_name_prefix=${{ env.TF_VAR_resource_name_prefix }}
          TF_VAR_image_tag=${{ env.TF_VAR_image_tag }}
          EOF

          env_file="templates/core/terraform/.env"
          cat <<EOF > $env_file
          TF_VAR_environment=${{ env.TF_VAR_environment }}
          TF_VAR_address_space=${{ env.TF_VAR_address_space }}
          EOF

    - name: Make bootstrap for terraform
      uses: azure/CLI@v1
      with:
        azcliversion: 2.20.0
        inlineScript: |
          make bootstrap
